spring.application.name=poketienda

# Datasource
spring.datasource.url=jdbc:mysql://localhost:3306/pokestore
spring.datasource.username=root
spring.datasource.password=

# Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true